import type { Fen } from '../value-objects/Fen.js';

export interface MoveProps {
  id?: bigint; // Optional because it is generated by mysql
  gameId: string;
  playerId: string;
  moveNumber: number;
  notation: string; // SAN notation
  fenAfter: Fen;
  timeTakenMs: number;
  createdAt?: Date;
}

export class Move {
  private props: MoveProps;

  private constructor(props: MoveProps) {
    this.props = {
      ...props,
      createdAt: props.createdAt || new Date(),
    };
  }

  public static create(
    gameId: string,
    playerId: string,
    moveNumber: number,
    notation: string,
    fenAfter: Fen,
    timeTakenMs: number,
  ): Move {
    return new Move({
      gameId,
      playerId,
      moveNumber,
      notation,
      fenAfter,
      timeTakenMs,
    });
  }

  public static reconstitute(props: MoveProps): Move {
    return new Move({ ...props });
  }

  public getId(): bigint | undefined {
    return this.props.id;
  }
  public getGameId(): string {
    return this.props.gameId;
  }
  public getPlayerId(): string {
    return this.props.playerId;
  }
  public getMoveNumber(): number {
    return this.props.moveNumber;
  }
  public getNotation(): string {
    return this.props.notation;
  }
  public getFenAfter(): Fen {
    return this.props.fenAfter;
  } // <-- Retorna o VO
  public getTimeTakenMs(): number {
    return this.props.timeTakenMs;
  }
  public getCreatedAt(): Date {
    return this.props.createdAt as Date;
  }
}
